import { Divider, Flex } from "@chakra-ui/react";
import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Messages, { Message } from "@/components/Messages";
import { runLlm } from "@/pages/api/utils";
import { dummyMessages } from "@/utils/dummyMessages";

const inter = Inter({ subsets: ["latin"] });

let count = 0;

export default function Home() {
  const [prompt, setPrompt] = useState<string>("");
  const [llmtext, setLlmtext] = useState<string>("");
  const [messages, setMessages] = useState<Message[]>(dummyMessages.data);
  const [inputMessage, setInputMessage] = useState("");

  const onSwitch = (prompt: string) => {
    if (prompt === "") return;
    runLlm(prompt)
      .then((llm) => {
        setLlmtext(llm);
      })
      .catch((error) => {
        console.error("An error occurred while running LLM:", error);
      });
    count++;
    console.log(`count: ${count}`);
  };

  const handleSendMessage = () => {
    if (!inputMessage.trim().length) {
      return;
    }
    const data = inputMessage;

    setMessages((old) => [...old, { from: "me", text: data }]);
    setInputMessage("");

    setTimeout(() => {
      setMessages((old) => [...old, { from: "computer", text: data }]);
    }, 1000);
  };

  return (
    <Flex w="100%" h="100vh" justify="center" align="center">
      <Flex w="40%" h="90%" flexDir="column">
        <Header />
        <Divider />
        <Messages messages={messages} />
        <Divider />
        <Footer
          inputMessage={inputMessage}
          setInputMessage={setInputMessage}
          handleSendMessage={handleSendMessage}
        />
      </Flex>
    </Flex>
  );
}

// <>
//   <Head>
//     <title>Create Next App</title>
//     <meta name="description" content="Generated by create next app" />
//     <meta name="viewport" content="width=device-width, initial-scale=1" />
//     <link rel="icon" href="/favicon.ico" />
//   </Head>
//   <main className={styles.main}>
//     <div className={styles.description}>
//       <p>
//         Get started by editing&nbsp;
//         <code className={styles.code}>src/pages/index.tsx</code>
//       </p>
//       <div>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           By{" "}
//           <Image
//             src="/vercel.svg"
//             alt="Vercel Logo"
//             className={styles.vercelLogo}
//             width={100}
//             height={24}
//             priority
//           />
//         </a>
//       </div>
//     </div>

//     <div className={styles.center}>
//       {/* <Image
//         className={styles.logo}
//         src="/next.svg"
//         alt="Next.js Logo"
//         width={180}
//         height={37}
//         priority
//       /> */}
//       {llmtext}
//     </div>
//     <textarea
//       rows={2}
//       cols={100}
//       onChange={(e) => setPrompt(e.target.value)}
//     />
//     <button
//       className={styles.button}
//       onClick={() => onSwitch(prompt)}
//       disabled={prompt === ""}
//     >
//       送信
//     </button>
//     <div className={styles.grid}>
//       <a
//         href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//         className={styles.card}
//         target="_blank"
//         rel="noopener noreferrer"
//       >
//         <h2 className={inter.className}>
//           Docs <span>-&gt;</span>
//         </h2>
//         <p className={inter.className}>
//           Find in-depth information about Next.js features and&nbsp;API.
//         </p>
//       </a>

//       <a
//         href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//         className={styles.card}
//         target="_blank"
//         rel="noopener noreferrer"
//       >
//         <h2 className={inter.className}>
//           Learn <span>-&gt;</span>
//         </h2>
//         <p className={inter.className}>
//           Learn about Next.js in an interactive course with&nbsp;quizzes!
//         </p>
//       </a>

//       <a
//         href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//         className={styles.card}
//         target="_blank"
//         rel="noopener noreferrer"
//       >
//         <h2 className={inter.className}>
//           Templates <span>-&gt;</span>
//         </h2>
//         <p className={inter.className}>
//           Discover and deploy boilerplate example Next.js&nbsp;projects.
//         </p>
//       </a>

//       <a
//         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//         className={styles.card}
//         target="_blank"
//         rel="noopener noreferrer"
//       >
//         <h2 className={inter.className}>
//           Deploy <span>-&gt;</span>
//         </h2>
//         <p className={inter.className}>
//           Instantly deploy your Next.js site to a shareable URL
//           with&nbsp;Vercel.
//         </p>
//       </a>
//     </div>
//   </main>
// </>
